### ISSUE TITLE
About required environment variables

### ISSUE THREAD

**Issue by SizheWei** [autonomousvision/navsim#1]
Hi! Thank you for this incredible work! I'd like to clarify the proper method of setting up the necessary environment variables according to your README documentation located here: <https://github.com/autonomousvision/navsim/blob/main/docs/install.md#2-install-the-navsim-devkit>.

After following your guide to prepare the dataset and code, I have reached the stage where I need to define the paths for the environment variables. However, I am uncertain about the specific directories to use for each of the following:

```
export NAVSIM_DEVKIT_ROOT=/path/to/navsim/devkit  # Should this be the path to the root directory of my navsim installation?
export NUPLAN_EXP_ROOT=/path/to/navsim/exp # Is this the path pointing to the 'navsim_logs' folder that I've downloaded?
export NUPLAN_MAPS_ROOT=/path/to/nuplan/maps # The path to the downloaded 'nuplan-maps-v1.0' folder?
export OPENSCENE_DATA_ROOT=/path/to/openscene # Do I need to acquire a separate dataset specifically for this variable?
``` 

Your guidance in specifying these paths would be greatly appreciated!

**Comment by mh0797** [comment]
Hi @SizheWei,

The environment variables depend on where the dataset etc. are located.
In the following, I will assume your folder structure is as follows:
```angular2html
~/navsim_workspace
├── navsim (containing the devkit)
├── exp
└── dataset
    ├── maps
    ├── navsim_logs
    │    ├── mini
    │    └── trainval
    └── sensor_blobs
         ├── mini
         └── trainval

```
In the current version you only need to set the following environment variables:
```
export NUPLAN_MAPS_ROOT="$HOME/navsim_workspace/dataset/maps"
export NUPLAN_EXP_ROOT="$HOME/navsim_workspace/exp"
export NAVSIM_DEVKIT_ROOT="$HOME/navsim_workspace/navsim"
export OPENSCENE_DATA_ROOT="$HOME/navsim_workspace/dataset"
```
In the current version, you also need to directly set  `LOG_PATH=~/navsim_workspace/dataset/navsim_logs/mini` or `LOG_PATH=~/navsim_workspace/dataset/navsim_logs/trainval` in the scripts for [metric caching](https://github.com/autonomousvision/navsim/blob/main/scripts/run_metric_caching.sh#L2) and running the [pdm-scoring](https://github.com/autonomousvision/navsim/blob/main/scripts/run_pdm_score_evaluation.sh#L1).

You will find the metric cache in "~/navsim_workspace/exp/metric_cache" after running the script. Thus, when running the pdm-scoring, you can set `METRIC_CACHE_PATH=~/navsim_workspace/exp/metric_cache` [here](https://github.com/autonomousvision/navsim/blob/main/scripts/run_pdm_score_evaluation.sh#L2)


We will soon update our installation instructions to make this clearer. 
Thank you for pointing this out.

Let me know if you have further questions!

**Comment by SizheWei** [comment]
Thanks @mh0797 ! I got it now!
