### ISSUE TITLE
Aligning lidar points‘ coordinates across different frames？

### ISSUE THREAD

**Issue by woxihuanjiangguo** [autonomousvision/navsim#10]
Currently, I am using ego2global transformation matrix to warp LiDAR points’ in the history to the current key frame. If this matrix isn’t available in the final test set, it might be difficult to do so. Can you provide the transformation matrix between different frames for the test set?

**Comment by mh0797** [comment]
Hi @woxihuanjiangguo,

we don’t provide ego2global transformations in the AgentInputs for the test set to prevent leakage of ground truth map Information.

However, the ego history contains the displacement over the past timesteps. Thus the lidar points can be projected into the current frame by shifting and rotating them according to these displacements.
