### ISSUE TITLE
Question about driving direction compliance

### ISSUE THREAD

**Issue by woxihuanjiangguo** [autonomousvision/navsim#14]
Hi! I find this line of code calculating the Driving Direction Compliance metric a bit confusing:https://github.com/autonomousvision/navsim/blob/8af06bd77c58396c675cc5f7e3255efa6f3ac7cf/navsim/planning/simulation/planner/pdm_planner/scoring/pdm_scorer.py#L422-L428  It seems `oncoming_progress` is of shape [Num_proposals, 1 + Num_poses], but you slice its first dimension with some variables like time and horizons? So you are calculating the sum of different proposals? I don't understand, please help me, thanks!

**Comment by DanielDauner** [comment]
Thanks for pointing this out!

This is indeed a bug where oncoming progress is accumulated over the wrong dimension. As a side-effect, the ‘driving direction compliance’ sub-score gives (from what we can tell) always a perfect score, which is equivalent to skipping the sub-score altogether (see [`docs/metrics.md`](https://github.com/autonomousvision/navsim/blob/main/docs/metrics.md#understanding-the-pdm-score))

We decided to ignore the sub-score for the challenge and we will ensure no leaderboard submission will have a disadvantage from the metric. Participants do not have to re-submit. After the challenge, the sub-score will either be fixed or removed. 

Best,
Daniel

**Comment by woxihuanjiangguo** [comment]
I see. Thanks for your reply!
