### ISSUE TITLE
What's the coordinate system origin of the ego vehicle

### ISSUE THREAD

**Issue by woxihuanjiangguo** [autonomousvision/navsim#16]
Hi! Just want to ask what's the coordinate system origin of the ego vehicle? Is it the center of the rear? or something else

**Comment by DanielDauner** [comment]
Hi @woxihuanjiangguo, 

In NAVSIM, we use the rear axle as the origin of the ego frame. For example, the trajectories, bounding box annotations, LiDAR point cloud, and more are in this frame. Other parts use the global coordinates, e.g.,  the HD map or evaluation with the PDM Score. 

I hope that helps! 

Best,
Daniel

**Comment by woxihuanjiangguo** [comment]
Thanks a lot!

**Comment by Wolfybox** [comment]
> Hi @woxihuanjiangguo,
> 
> In NAVSIM, we use the rear axle as the origin of the ego frame. For example, the trajectories, bounding box annotations, LiDAR point cloud, and more are in this frame. Other parts use the global coordinates, e.g., the HD map or evaluation with the PDM Score.
> 
> I hope that helps!
> 
> Best, Daniel

Hi,

Does ego frame mean "front x, right y and z up"？

What is the coord system (origin and axis) of global coordinates?

**Comment by DanielDauner** [comment]
Hi @Wolfybox, the ego frame is 

- **Origin:** Center of the rear axle of the vehicle.
- **Axes:**
X-axis: Points forward along the direction of the vehicle.
Y-axis: Points to the left side of the vehicle's forward direction.
Z-axis: Points upwards perpendicular to the ground.

Not entirely sure, but from what I can tell, nuPlan is therefore in ISO 8855 norm. The global coordinate system depends on the map itself. Pretty sure the X-axis points east, whereas the Y-axis points north. 

Hope that was helpful!
Daniel

**Comment by Wolfybox** [comment]
> Hi @Wolfybox, the ego frame is
> 
> * **Origin:** Center of the rear axle of the vehicle.
> * **Axes:**
>   X-axis: Points forward along the direction of the vehicle.
>   Y-axis: Points to the left side of the vehicle's forward direction.
>   Z-axis: Points upwards perpendicular to the ground.
> 
> Not entirely sure, but from what I can tell, nuPlan is therefore in ISO 8855 norm. The global coordinate system depends on the map itself. Pretty sure the X-axis points east, whereas the Y-axis points north.
> 
> Hope that was helpful! Daniel

Very helpful. 

Thank you!
