### ISSUE TITLE
About download_navtrain.sh

### ISSUE THREAD

**Issue by pirotyyy** [autonomousvision/navsim#19]
Hi, I would like to download the navtrain datasets by running the code [download_navtrain.sh](https://github.com/autonomousvision/navsim/blob/main/download/download_navtrain.sh).
However, I got following outputs while downloading it.

```bash
mv: cannot move 'history_split_1/2021.06.09.14.03.17_veh-12_00159_00283' to 'trainval_sensor_blobs/trainval/2021.06.09.14.03.17_veh-12_00159_00283': Directory not empty
```

**Note**:  This output was obtained for all the data in the history_split_1 directory. The one shown is just an example.

Upon checking the download logs, it seems that the data included in history_split might already be obtained when downloading the current_split.

**Comment by mh0797** [comment]
Hi @pirotyyy,

Thanks for pointing this out. The data in the history_split archives is not included in the current_split downloads. However, the scenes in the history split belong to the same log files as the current split scenes, as they cover the frames directly before the current_split scenes. As the folder-structure sorts the sensor data by scenes and log files, you cannot simply move the log file folder from the history_split to the trainval directory. Instead, you have to integrate them into the existing folder, i.e., you need to copy the folder corresponding to the scene into the respective log file folder. 
Replacing `mv` with `rsync` should do the trick.

Note that you only need to download the history_split if you want to train video agents.

I am closing this for now - feel free to re-open if the issue persists
