### ISSUE TITLE
About run_metric_caching.sh

### ISSUE THREAD

**Issue by efemantarci** [autonomousvision/navsim#20]
In this file cache file is written like this
`cache.cache_path=/home/aah1si/openscene/exp/public_test_metric_cache `
I think it should use exported values instead of /home/aah1si
So wouldn't this be better?
`cache.cache_path=$NAVSIM_EXP_ROOT/metric_cache `

**Comment by DanielDauner** [comment]
Hey @efemantarci, thanks for pointing this out. This is a typo and is already scheduled to be removed. 

You're correct; `cache.cache_path=$NAVSIM_EXP_ROOT/metric_cache` should be used in the script.
