### ISSUE TITLE
What labels should custom dataset provide when used with NAVSIM?

### ISSUE THREAD

**Issue by hollow-503** [autonomousvision/navsim#21]
I want to use NAVSIM with my custom dataset that provides images, LiDAR point cloud, 3D bouding box annotation and annotated HD map. Could you give me some instructions on adapting NAVSIM to my own custom dataset?

**Comment by DanielDauner** [comment]
Hi @hollow-503 

Thanks for your interest in our project! 

In theory, you can adjust your data set/loading to fit our dataclass interfaces in [`dataclass.py`](https://github.com/autonomousvision/navsim/blob/main/navsim/common/dataclasses.py). I would expect that implementing the HD-Map (used for the PDM-Score) will be most challenging. We use the nuPlan HD-Map, which has an abstract class called [`AbstractMap`](https://github.com/motional/nuplan-devkit/blob/master/nuplan/common/maps/abstract_map.py#L23). You can create a new map class, inheriting from the abstract class, and use it in NAVSIM instead.

It might take some effort to adapt NAVSIM for a different dataset. If you come across technical or specific problems, feel free to reach out to me via E-Mail: daniel.dauner@uni-tuebingen.de

Best,
Daniel
