### ISSUE TITLE
Is the 'classic' Transfuser or Transfuser++ implemented in the repo?

### ISSUE THREAD

**Issue by LaCandela** [autonomousvision/navsim#22]
Is the 'classic' Transfuser or Transfuser++ implemented in the repo?

**Comment by DanielDauner** [comment]
Hi @LaCandela 

The code is based on [CARLA Garage](https://github.com/autonomousvision/carla_garage), so the main structure is taken from TransFuser++. However, our NAVSIM version does implement a different mapping, detection, and trajectory head. The implementation might overall be most similar to [PAMI TransFuser](https://arxiv.org/abs/2205.15997).

Best,
Daniel
