### ISSUE TITLE
When does the test server on huggingface restart? 

### ISSUE THREAD

**Issue by tongyuyu** [autonomousvision/navsim#23]
When does the test server on huggingface restart? Or can I get a fair test score offline?

**Comment by DanielDauner** [comment]
We are currently working on a NAVSIM v1.1 release, which includes a re-opened leaderboard on hugging face. This leaderboard will likely evaluate the `navtest` split. Please stay tuned for updates. In the meantime, we recommend using the `navtest` split offline for benchmarking and comparisons in research papers.
