### ISSUE TITLE
about navtrain and logs

### ISSUE THREAD

**Issue by mikucc** [autonomousvision/navsim#27]
thanks for your job,and when i try to use your dataset to train my model,it happens

FileNotFoundError: [Errno 2] No such file or directory: '/home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_F0/d80accf581f75dc1.jpg'

I checked the downloaded dataset, and the folder navtrain_history_1 is indeed missing the specified image file.so i want to know if navtrain and trainval_logs require additional steps to align, or if simply changing the TRAIN_TEST_SPLIT to navtrain is enough. Could the issues I'm encountering be solely due to errors in my downloaded dataset?
thanks！

**Comment by mikucc** [comment]
hi,@DanielDauner ,thanks for your reply.
I tried to re-download navtrain_history_1, but after unzipping it, I still couldn't find the image named d80accf581f75dc1.
Normally, this shouldn't be the problem, but I downloaded it directly from https://s3.eu-central-1.amazonaws.com/avg-projects-2/navsim/navtrain_history_1.tgz.

**Comment by mikucc** [comment]
@DanielDauner hi,Could you provide the MD5sums for the dataset so that I can verify whether the data I downloaded is complete and wasn't corrupted due to network issues? thanks

**Comment by mikucc** [comment]
I tried downloading the dataset three times (it’s very slow, taking about 10 hours each time). Eventually, I tried resolving the issue by deleting the missing file names from the train_log. In fact, only the folder 2021.06.14.16.48.02_veh-12_01732_01853 was missing datas

Warning: Image file /home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_F0/7f5a530d0f545135.jpg does not exist, skipping cam_f0
Warning: Image file /home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_L0/5834dff9dde95828.jpg does not exist, skipping cam_l0
Warning: Image file /home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_R0/961a7bd4a47d5f1e.jpg does not exist, skipping cam_r0
Warning: Image file /home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_L1/3b5ffebe1ef95f80.jpg does not exist, skipping cam_l1
Warning: Image file /home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_R1/37ec59f4b9cf503a.jpg does not exist, skipping cam_r1
Warning: Image file /home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_L2/923ad035449e5680.jpg does not exist, skipping cam_l2
Warning: Image file /home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_R2/bfb26e770a4d58a1.jpg does not exist, skipping cam_r2
Warning: Image file /home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_B0/a5b18a87a8ce5b22.jpg does not exist, skipping cam_b0
Warning: Lidar file /home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/MergedPointCloud/94fcd4c557e0589c.pcd does not exist, skipping lidar data.


i dont know why, but i will close this issue

**Comment by DanielDauner** [comment]
Hi @mikucc 

We are sorry for the complications you experienced while downloading `navtrain`. We have previously verified that the files are complete and don't provide MD5sums. 

However, we are looking into the issue and trying to reproduce the problem. 

Best,
Daniel

**Comment by hongxiaoy** [comment]
> thanks for your job,and when i try to use your dataset to train my model,it happens
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_F0/d80accf581f75dc1.jpg'
> 
> I checked the downloaded dataset, and the folder navtrain_history_1 is indeed missing the specified image file.so i want to know if navtrain and trainval_logs require additional steps to align, or if simply changing the TRAIN_TEST_SPLIT to navtrain is enough. Could the issues I'm encountering be solely due to errors in my downloaded dataset? thanks！

Hello, I'm faced with the same problem, and many logs report FileNotFoundError.
Which scripts have you used to download the data for navtrain splits? Thansk.

**Comment by mikucc** [comment]
> > thanks for your job,and when i try to use your dataset to train my model,it happens
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_F0/d80accf581f75dc1.jpg'
> > I checked the downloaded dataset, and the folder navtrain_history_1 is indeed missing the specified image file.so i want to know if navtrain and trainval_logs require additional steps to align, or if simply changing the TRAIN_TEST_SPLIT to navtrain is enough. Could the issues I'm encountering be solely due to errors in my downloaded dataset? thanks！
> 
> Hello, I'm faced with the same problem, and many logs report FileNotFoundError. Which scripts have you used to download the data for navtrain splits? Thansk.

I used download_navtrain.sh to download the dataset. Based on my experience, first, make sure that the train_test_split is using navtrain instead of trainval. Then try removing the folders that are causing errors from the dataset split, such as the default default_train_val_test_log_split.yaml (as I mentioned above, I only had to remove one folder to resolve the issue).

**Comment by hongxiaoy** [comment]
> > > thanks for your job,and when i try to use your dataset to train my model,it happens
> > > FileNotFoundError: [Errno 2] No such file or directory: '/home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_F0/d80accf581f75dc1.jpg'
> > > I checked the downloaded dataset, and the folder navtrain_history_1 is indeed missing the specified image file.so i want to know if navtrain and trainval_logs require additional steps to align, or if simply changing the TRAIN_TEST_SPLIT to navtrain is enough. Could the issues I'm encountering be solely due to errors in my downloaded dataset? thanks！
> > 
> > 
> > Hello, I'm faced with the same problem, and many logs report FileNotFoundError. Which scripts have you used to download the data for navtrain splits? Thansk.
> 
> I used download_navtrain.sh to download the dataset. Based on my experience, first, make sure that the train_test_split is using navtrain instead of trainval. Then try removing the folders that are causing errors from the dataset split, such as the default default_train_val_test_log_split.yaml (as I mentioned above, I only had to remove one folder to resolve the issue).

You mean you changed the original training dataset??? Just ignore that log? But this might not fit my situation, many logs produced file not found error in my terminal.

**Comment by hongxiaoy** [comment]
> > > thanks for your job,and when i try to use your dataset to train my model,it happens
> > > FileNotFoundError: [Errno 2] No such file or directory: '/home/williem/navsim_workspace/dataset/sensor_blobs/trainval/2021.06.14.16.48.02_veh-12_01732_01853/CAM_F0/d80accf581f75dc1.jpg'
> > > I checked the downloaded dataset, and the folder navtrain_history_1 is indeed missing the specified image file.so i want to know if navtrain and trainval_logs require additional steps to align, or if simply changing the TRAIN_TEST_SPLIT to navtrain is enough. Could the issues I'm encountering be solely due to errors in my downloaded dataset? thanks！
> > 
> > 
> > Hello, I'm faced with the same problem, and many logs report FileNotFoundError. Which scripts have you used to download the data for navtrain splits? Thansk.
> 
> I used download_navtrain.sh to download the dataset. Based on my experience, first, make sure that the train_test_split is using navtrain instead of trainval. Then try removing the folders that are causing errors from the dataset split, such as the default default_train_val_test_log_split.yaml (as I mentioned above, I only had to remove one folder to resolve the issue).

In short, running the `download_navtrain.sh` only is enough, right? And the `navtrain.yaml` just leave it there and don't need change anything?
