### ISSUE TITLE
About the training set

### ISSUE THREAD

**Issue by woxihuanjiangguo** [autonomousvision/navsim#3]
Hi, may I ask how large the training set is and when will it be released?

**Comment by kashyap7x** [comment]
Hello! NAVSIM uses the OpenScene dataset. The full trainval split of this data is currently available on the [OpenScene repository](https://github.com/OpenDriveLab/OpenScene/tree/main):
https://github.com/OpenDriveLab/OpenScene/blob/main/docs/getting_started.md#trainval-set

Its size is approximately 2TB. We are working on preparing a download script as well as a subsampled version of this data for training (around 300GB). These are expected to be released by the end of March.

**Comment by woxihuanjiangguo** [comment]
Thanks for your prompt reply!!
