### ISSUE TITLE
skipping directory of `rsync` command

### ISSUE THREAD

**Issue by hongxiaoy** [autonomousvision/navsim#31]
When I run https://github.com/autonomousvision/navsim/blob/2623b40b587d93ac4d66b54594cc0f33a9e0051a/download/download_navtrain.sh#L14 this line, the output from terminal is `skipping directory ...`. I changed `-v` to `-rv` then it's successful to merge directories.

I'm not sure if this happened in others machine. Is this needed to be updated?

**Comment by DanielDauner** [comment]
Hi @hongxiaoy

Thanks for your message. I will try to reproduce that issue and adapt the download script if needed. It might depend on the system.

Best
Daniel
