### ISSUE TITLE
Question about the run_transfuser.sh for evaluating transfuser agent

### ISSUE THREAD

**Issue by RexGPT** [autonomousvision/navsim#32]
Hello! Thank you for your excellent work! I have a question about [this line](https://github.com/autonomousvision/navsim/blob/main/scripts/evaluation/run_transfuser.sh#L7C1-L7C34) in the Transfuser evaluation script. It appears that the single_machine_thread_pool setting uses all available threads for evaluation. However, while the evaluation process runs in parallel on the CPU, it seems to utilize only a single GPU, which eventually leads to running out of single GPU memory.

Did I misconfigure something to distribute the parallel evaluation across multiple GPUs, or is it intended that the parallel evaluation process runs on just one GPU?

@DanielDauner Looking forward to your reply!

**Comment by DanielDauner** [comment]
Hi @RexGPT 

Thanks for your interest and this question!

Running evaluations in parallel over CPU and GPU processes simultaneously is tricky. We currently do not have a mechanism to run the PDM-Score and pre-processing on multiple CPU threads while only utilizing one GPU process. (I am no expert in this, but I'd assume this to be a challenge regarding syncing and communicating between CPU/GPU processes). As a result, finding the right `worker` (for CPU multiprocessing) and GPU utilization depends on your system specification. 

In your case, you could try to reduce the parallel processes with `worker.max_workers=N`, where your model fits `N`-times into GPU memory. Using only the CPU for the evaluation can also be fast if you have many CPU cores and a lot of RAM, (e.g., with `worker={ray_distributed, single_machine_thread_pool}`)

In the example script, we evaluated TransFuser on a system with 32 CPU threads, 32 GiB RAM, and 24 GiB GPU memory, where the standard setting was fairly fast and stable.

I hope that helps! 
Daniel

**Comment by RexGPT** [comment]
Hi Daniel @DanielDauner  , thanks for your quick response! I’ve noticed that when using the SingleMachineParallelExecutor (`worker=single_machine_thread_pool`) worker, the maximum number of workers I can use on a 24GB GPU is 32, and the evaluation takes about 1 hour. However, when I switch to RayDistributedNoTorch (`worker=ray_distributed_no_torch`), I can set the worker count to 128, and it doesn’t require any GPU memory, reducing the evaluation time to around 30 minutes.

Is this expected behavior? From my comparison, it seems that the recommended `worker=single_machine_thread_pool` setting, which uses SingleMachineParallelExecutor, may not be the most efficient approach.

**Comment by DanielDauner** [comment]
Yes and No. As I mentioned, using only the CPU for the evaluation (as done with `worker={ray_distributed, ray_distributed_no_torch}`) can be the fastest option. This setting however requires a lot of RAM, which is why I disabled for our system.

Generally speaking, if you can run any NAVSIM script with the ray library, it's very likely the fastest options. Downsides of ray are high RAM usage and instabilities (specifically on SLURM clusters).

I hope that helps!
Daniel

**Comment by RexGPT** [comment]
Thanks for your detailed reply!

**Comment by ChuXX325** [comment]
> Hello! Thank you for your excellent work! I have a question about [this line](https://github.com/autonomousvision/navsim/blob/main/scripts/evaluation/run_transfuser.sh#L7C1-L7C34) in the Transfuser evaluation script. It appears that the single_machine_thread_pool setting uses all available threads for evaluation. However, while the evaluation process runs in parallel on the CPU, it seems to utilize only a single GPU, which eventually leads to running out of single GPU memory.
> 
> Did I misconfigure something to distribute the parallel evaluation across multiple GPUs, or is it intended that the parallel evaluation process runs on just one GPU?
> 
> [@DanielDauner](https://github.com/DanielDauner) Looking forward to your reply!

How did you evaluate it on a single GPU?
