### ISSUE TITLE
[Discussion] Similar PDMS scores for all e2e planner

### ISSUE THREAD

**Issue by Wolfybox** [autonomousvision/navsim#34]
In Table. 1 of the paper, LTF, transfuser, UniAD and ParaDrive achieve quite similar scores. I wonder whether this dataset or evaluation protocol is capable of distinguishing different e2e planners ? Or inherently these planners are similar in closed-loop performance?

**Comment by DanielDauner** [comment]
Hi @Wolfybox, we think that the performances of these models are rather inherently similar, as they are trained on the same training subset, with similar losses, etc. You can look at the [new leaderboard on Hugging Face](https://huggingface.co/spaces/AGC2024-P/e2e-driving-navsim), where the entries show more diverse results.

Best,
Daniel
