### ISSUE TITLE
server dead

### ISSUE THREAD

**Issue by ggosjw** [autonomousvision/navsim#36]
![601251730626874_ pic](https://github.com/user-attachments/assets/db5bbcf7-fed2-41a6-8809-af8684b23e32)
Dear author:

I encountered an issue while attempting to submit; the webpage displays the attached error, suggesting the server might be down. Could you please look into this?

Thank you very much for your assistance.

**Comment by DanielDauner** [comment]
@ggosjw The server seems to be running again. Does the issue still persist?

**Comment by ggosjw** [comment]
yes, it backs to normal. Thank you for your effort!

**Comment by ggosjw** [comment]
I encountered this issue again where it seems the server is in the process of rebooting. Does this mean I should simply wait for it to return to normal?
![image](https://github.com/user-attachments/assets/0884db05-702d-4cd0-9977-b0dc5ccc4eed)
Thank you for your kind help.
