### ISSUE TITLE
Batchwise implementation or GPU acceleration of pdm_score

### ISSUE THREAD

**Issue by hanfeng-wu** [autonomousvision/navsim#37]
Hi Thanks for the great work. I wonder if there will be any batch/gpu version of pdm_score(navim/evalutate/pdm_score.py.pdm_score) that I can for example deal with multiple trajectories and simulate them in parallel?

**Comment by mh0797** [comment]
Hi,
we don't support that at the moment and currently have no plans to add this feature in the near future. However, the PDM-Scorer and PDM-Simulator, i.e. the core components of the pdm_score function support batch-wise processing. I recommend having a closer look at them: It might be rather easy to implement a version of the pdm_score function that supports batched inputs.
