### ISSUE TITLE
Log Pickle Loading Fails

### ISSUE THREAD

**Issue by Dylan-LDR** [autonomousvision/navsim#4]
When I run ```./run_cv_pdm_score_evaluation.sh```, there is a bug when loading log file. I use the pickle files you provide.
![image](https://github.com/autonomousvision/navsim/assets/49780695/020d04b5-6716-4e7d-a3ad-8ad6b6b187e6)

**Comment by Dylan-LDR** [comment]
Indeed I find that the pickle loaded is a list of dictionaries. Did I do something wrong with the data?

**Comment by mh0797** [comment]
Hi @Dylan-LDR,

Which split are you trying to run?
The mini split or the test split?

**Comment by Dylan-LDR** [comment]
mini split

**Comment by mh0797** [comment]
When did you download the dataset? Did you use the download script provided in the devkit ?

**Comment by mh0797** [comment]
We recently had a change in the dataset format.
I will try to reproduce your issue and push a fix later if needed.

Thank you for pointing this out.

**Comment by mh0797** [comment]
The fix is pushed. Please let me know if you have any more problems.

**Comment by mh0797** [comment]
Closing the issue. Feel free to re-open if you face any more issues.
