### ISSUE TITLE
Data Downloading Issue

### ISSUE THREAD

**Issue by BlueCat-de** [autonomousvision/navsim#41]
In your installation instruction, there exist a `exp` folder in the data structure. However, after I downloaded the mini split, I can't find any folder related to this `exp`. So where can  I get it?

**Comment by DanielDauner** [comment]
Hi @BlueCat-de 

You can set the `exp` folder to any directory you want. The `exp` folder will contain all experiment results, e.g. when training or evaluating models. As stated in the [`install.md`](https://github.com/autonomousvision/navsim/blob/main/docs/install.md), you need to define a environment variable with 

```bash
export NAVSIM_EXP_ROOT="$HOME/navsim_workspace/exp"
```

Note that you can change the directory to your liking. The paths in the documentation are only a suggestion. Initially, you need to create the folder structure for the `exp` folder. It shouldn't be relevant when downloading the data splits. 

I hope that helps!
Daniel
