### ISSUE TITLE
Question about the private test set

### ISSUE THREAD

**Issue by woxihuanjiangguo** [autonomousvision/navsim#6]
Hi, I've downloaded the private test set downloaded from [https://huggingface.co/datasets/OpenDriveLab/OpenScene/resolve/main/openscene-v1.1/openscene_metadata_private_test_e2e.tgz](https://huggingface.co/datasets/OpenDriveLab/OpenScene/resolve/main/openscene-v1.1/openscene_metadata_private_test_e2e.tgz) and [https://huggingface.co/datasets/OpenDriveLab/OpenScene/resolve/main/openscene-v1.1/openscene_sensor_private_test_e2e.tgz](https://huggingface.co/datasets/OpenDriveLab/OpenScene/resolve/main/openscene-v1.1/openscene_sensor_private_test_e2e.tgz) according to your script. It seems that this private set is mainly based on the previous test set from [https://huggingface.co/datasets/OpenDriveLab/OpenScene/resolve/main/openscene-v1.1/openscene_metadata_test.tgz](https://huggingface.co/datasets/OpenDriveLab/OpenScene/resolve/main/openscene-v1.1/openscene_metadata_test.tgz)?

The previous test set contains annotations like bboxes and HD map according to [OpenScene](https://github.com/OpenDriveLab/OpenScene). I feel like asking how can we maintain the integrity of the challenge if these data are visible to participants?

**Comment by mh0797** [comment]
Hi,

We use a combination of public data and private test data to flag suspicious submissions.
However, the evaluation itself will be based on the private data, so that no bounding boxes or maps are available.

Note that the main award in the competition is the innovation award, which will be determined by double-blind reviews of submitted technical reports. Any attempt to cheat on the test set would result in disqualification.

**Comment by woxihuanjiangguo** [comment]
Thanks for the clarification. Another thing I would like to ask is that the private test data contains only about 600 frames, if I'm right, which is around 5 minutes in total? Wo
uldn't that be too short for the final evaluation?

**Comment by mh0797** [comment]
The evaluation is focused on meaningful and challenging frames without faulty annotations.
This way, the results on these frames are very indicative of the performance of a method.
The test set performance also generalizes well to the larger pubic test set.

**Comment by woxihuanjiangguo** [comment]
Thanks!
