### ISSUE TITLE
Inquiry About Future Plans for Handling Ego Past States in Model Inputs

### ISSUE THREAD

**Issue by robotfan4** [autonomousvision/navsim#8]
https://github.com/autonomousvision/navsim/blob/800cbd199bbfe31012c61a73d5b0af435af6aa87/navsim/planning/scenario_builder/navsim_scenario.py#L254
Hi, thanks for the great work, Could you please share if there are any plans to address this in the near future? As ego past states are input of model to be tested.

**Comment by DanielDauner** [comment]
Hi, the purpose of the `NavSimScenario` is currently only to define an interface to execute the PDM-Closed planner as part of running the metric. PDM-Closed doesn't need past ego states; thus, we only inserted a dummy. We will eventually refactor the code section (with low priority).

You can access past ego states in local coordinates in the [`AgentInput`](https://github.com/autonomousvision/navsim/blob/800cbd199bbfe31012c61a73d5b0af435af6aa87/navsim/common/dataclasses.py#L124) data class, which defines the input for the [`AbstractAgent`](https://github.com/autonomousvision/navsim/blob/800cbd199bbfe31012c61a73d5b0af435af6aa87/navsim/agents/abstract_agent.py#L9). The `AgentInput` contains a list of [`EgoStatus`](https://github.com/autonomousvision/navsim/blob/800cbd199bbfe31012c61a73d5b0af435af6aa87/navsim/common/dataclasses.py#L114) objects from past steps, which include the ego pose. 

Best, Daniel
